@"
name: CD - Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
    paths:
      - "app/**"
      - "model/**"
      - "results/**"
      - "requirements.txt"
      - ".github/workflows/cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install HF CLI
        run: pip install -U "huggingface_hub[cli]"
      - name: Login to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential
      - name: Upload to Space
        run: |
          huggingface-cli upload TU_USUARIO/Drug-Classification ./app --repo-type=space --commit-message="Sync App"
          huggingface-cli upload TU_USUARIO/Drug-Classification ./model /Model --repo-type=space --commit-message="Sync Model"
          huggingface-cli upload TU_USUARIO/Drug-Classification ./results /Metrics --repo-type=space --commit-message="Sync Metrics"
"@ | Set-Content .github/workflows/cd.yml
