name: CD - Deploy to Hugging Face Space

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install HF CLI
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub[cli]"

      - name: Login to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential

      - name: Upload to Space
        run: |
          huggingface-cli upload laurilla1207/Drug-Classification ./requirements.txt /requirements.txt --repo-type=space --commit-message "Sync requirements"
          huggingface-cli upload laurilla1207/Drug-Classification ./App --repo-type=space --commit-message "Sync App"
          huggingface-cli upload laurilla1207/Drug-Classification ./Model /Model --repo-type=space --commit-message "Sync Model"
          huggingface-cli upload laurilla1207/Drug-Classification ./Results /Metrics --repo-type=space --commit-message "Sync Metrics"

